import React, {useState, useEffect}  from 'react'
import './Conway.css'


const Game = () => {
   
   const numRows = 60
   const numCols = 60



   
   const [grid, setGrid] = useState()
   
   // Creates array gird based of dimensions of above varibles 
   const createGrid = () => {
      let grid = [];
         for (let i = 0; i < numRows; i++) {
            let row = [];
         for(let k = 0; k < numCols; k++) {
            row.push(0)
         }
            grid.push(row)
         }
      return grid
   }
   

   // updates state on load with random grid generated by above function
   useEffect(() => {
      setGrid(createGrid())
   }, [])

   return (
      <div className="game-container">
         <div className="game-area">
            {grid &&
               grid.map((rows, i) =>
               rows.map((col, k) => (
                  <div key={k} style={{
                     width: 10,
                     height: 10,
                     backgroundColor: grid[i][k] ? "green" : "",
                     border: "1px solid black",
                  }}/>
               ))
          )}
         </div>
      </div>
   )
}

export default Game


